blank_issues_enabled: true
contact_links:
  - name: Discussion
    url: https://github.com/Rigorous-ly/rigorously/discussions
    about: Ask questions, share how you use Rigorously, suggest improvements
